host: 0.0.0.0
plugins:
  - generator_scss
sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown
exclude:
  - README.md
  - config.rb
  - CNAME
  - Gemfile
  - Gemfile.lock
  - tags
  - script
site_title: "Amsterdam.rb"
slack_app: "https://slack.amsrb.org"
youtube_channel_url: "https://www.youtube.com/channel/UCyExf-593j4hjN_cFCSnr2w"
